development:
  cloud_name: <%= Rails.application.credentials.dig(:Cloudnariy, :cloud_name) %>
  api_key: <%= Rails.application.credentials.dig(:Cloudnariy, :api_key) %>
  api_secret: <%= Rails.application.credentials.dig(:Cloudnariy, :api_secret) %>
  secure: true
production:
  cloud_name: <%= Rails.application.credentials.dig(:Cloudnariy, :cloud_name) %>
  api_key: <%= Rails.application.credentials.dig(:Cloudnariy, :api_key) %>
  api_secret: <%= Rails.application.credentials.dig(:Cloudnariy, :api_secret) %>
  secure: true
